### ISSUE TITLE
Notification Banner Size Changing Feature

### ISSUE THREAD

**Issue by ICUBE321** [Platonenkov/Notification.Wpf#32]
Hey, 

I'm using the notification banner on a large, high resolution device so although the font size is large enough to read, the size of the notification banner comes up as too small and the text that's being displayed gets cut off. Can you add a method of maybe changing/increasing the size of the banner or making it large enough relative to the user's screen resolution?

Thank you.

**Comment by Platonenkov** [comment]
> I'm using the notification banner on a large, high resolution device so although the font size is large enough to read, the size of the notification banner comes up as too small and the text that's being displayed gets cut off. Can you add a method of maybe changing/increasing the size of the banner or making it large enough relative to the user's screen resolution?

Hi, this has already been implemented, please see Issue https://github.com/Platonenkov/Notification.Wpf/issues/14
In a future I will add it to documentation

```C#
NotificationConstants.MinWidth = 350;
NotificationConstants.MaxWidth = 700;
```

**Comment by ICUBE321** [comment]
Alright, seen it. Thanks
