### ISSUE TITLE
Set custom position

### ISSUE THREAD

**Issue by rickgoud** [Platonenkov/Notification.Wpf#34]
Hi,

we want to show a notification inside Outlook Desktop on the top right part of the compose window. This is not under our control, but we can find out the X and Y position the top right part of the toast should be started to be displayed. Is it possible to show the toast at a custom location as the top right X, Y coordinate?

Thanks for your help!

**Comment by Platonenkov** [comment]
Hi,
You can insert area in place where you need in you application.
```xaml
<Grid>
    <Grid.ColumnDefinitions>
        <ColumnDefinitions/>
        <ColumnDefinitions/>
        <ColumnDefinitions/>
    </Grid.ColumnDefinitions>
<notifications:NotificationArea Grid.Column="2" x:Name="WindowArea" Position="TopLeft" MaxItems="3"/>
</Grid>
```

```C#
notificationManager.Show(title, Message, type, "WindowArea", onClick: () => SomeAction();
```

and message will position in 3 column

location by coordinates is currently unavailable, I will include this in the plan, or you can implement and send Merge

**Comment by rickgoud** [comment]
Hi,

Thanks for the quick reply. As the Outlook (or Word, or Powerpoint, etc) window is not 'ours' we can most likely not do that, but will experiment. Any tips/tricks where to start if we can to support specifying/overriding the coordinate of TopRight, TopLeft, etc?
Thanks!

**Comment by Platonenkov** [comment]
> Any tips/tricks where to start if we want to support specifying/overriding the coordinate of TopRight, TopLeft, etc?

[This class](https://github.com/Platonenkov/Notification.Wpf/blob/dev/Notification.Wpf/Base/NotificationManager.cs)

in the row 356
![image](https://user-images.githubusercontent.com/44946855/143733911-e110b2ad-50e2-439b-bb30-e3673e7ab01e.png)

[this style](https://github.com/Platonenkov/Notification.Wpf/blob/dev/Notification.Wpf/Themes/Generic.xaml)

![image](https://user-images.githubusercontent.com/44946855/143734082-7b6d818e-153e-41f4-b7a9-129140bb06a3.png)


I see it like this:

create another 1 [position type](https://github.com/Platonenkov/Notification.Wpf/blob/dev/Notification.Wpf/Controls/NotificationPosition.cs) (abstract).
Start the static variable Position, and if you select abstract, let the coordinates be set

**Comment by Platonenkov** [comment]
Ok, from version `6.1.0.0` now `this feature work` normal.
![image](https://user-images.githubusercontent.com/44946855/144111953-e7c656b7-d403-42cc-af1f-d7c2806dd3a1.png)

so, you can set Message position as `Absolute`, and set `NotificationConstants.AbsolutePosition`
but, You must set base corner for position margin.
Sample:
```
NotificationConstants.AbsolutePosition.X = 50D;
NotificationConstants.AbsolutePosition.Y = 100D;
NotificationConstants.AbsolutePosition.BaseCorner= Corner.TopRight;
```

And now you can set reversed panel setting for message stack:  
Use `NotificationConstants.IsReversedPanel` to change stack orientation. Set as `null to default`.

you can play with it in the sample project.

**Comment by Platonenkov** [comment]
https://github.com/Platonenkov/Notification.Wpf/commit/954c89ae45644e567983849d54c37fec37d300bb

[Release 6.1.0.0](https://github.com/Platonenkov/Notification.Wpf/releases/tag/v6.1.0.0)
if this version is Ok for you close this discussion please

**Comment by rickgoud** [comment]
Wow @Platonenkov ; you are a rockstar!! I will check it out in the coming days!

**Comment by rickgoud** [comment]
It seems to work perfectly, but, it seems that if I update the message position constant after setting is for the first time, the location is never updated. Is that correct?
So example.

Is set: NotificationConstants.MessagePosition = Notification.Wpf.Controls.NotificationPosition.Center;

Upon the first message, the message is displayed in the Center as it supposed to do. Now I put a breakpoint at that line and for the next toast I update the code to: NotificationConstants.MessagePosition = Notification.Wpf.Controls.NotificationPosition.TopRight (or any other value).
This doesn't result in showing the next message in the TopRight corner, but every message, whatever I change, stays in the Center, until I restart. For absolute window position where the user might resize or move his/her window, allowing to update the location is essential. Am I doing something wrong here?

Thanks!

**Comment by Platonenkov** [comment]
> This doesn't result in showing the next message in the TopRight corner, but every message, whatever I change, stays in the Center, until I restart.

All correct, the position of messages in the window can be changed only after it is reset, the reset occurs when there are no messages in the window.

**Comment by rickgoud** [comment]
Hey! All my messages in the window area clear visually, but is there some list I can/need to check or reset manually? Maybe because of my previous error the list is not properly updated/cleared?

**Comment by Platonenkov** [comment]
message is removed from the list when "Close" is executed on it
when there are no active messages in the stack, the window closes

**Comment by rickgoud** [comment]
With the context above, working as expected; Awesome!
