### ISSUE TITLE
Exception thrown upon notification close

### ISSUE THREAD

**Issue by rickgoud** [Platonenkov/Notification.Wpf#35]
Hi. me again!

I'm a trying your awesome library. but keep on running into exceptions thrown when the noticafaction closes after x second.
See below. I also imported your project to see if I could find the root cause, but not successful. only thing I see is that it happens upon onclose; Seemingly related to threading or so, which could make sense as your application uses UI thread also used by the source application, but must be a solvable problem?
Let me know how I can help debug or so!

Exception thrown: 'System.NullReferenceException' in Notification.Wpf.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
({0}: {1}, System.NullReferenceException: Object reference not set to an instance of an object.
   at Notification.Wpf.Controls.Notification.<Close>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) :: Dispatcher_UnhandledException in line 55 on thread 11, Info)
Exception thrown: 'System.NullReferenceException' in WindowsBase.dll

**Comment by Platonenkov** [comment]
hi, unfortunately I couldn't repeat this mistake.

moreover, I cleared the project and cache, reassembled and everything works perfectly

but, if you have a thread exception, you can use constructor with dispatcher:
```C#
/// <summary>
/// Initialize new notification manager
/// </summary>
/// <param name="dispatcher">dispatcher for manager (can be null)</param>
public NotificationManager(Dispatcher dispatcher = null)
{
    dispatcher ??= Application.Current?.Dispatcher ?? Dispatcher.CurrentDispatcher;

    _dispatcher = dispatcher;
}
```

**Comment by Platonenkov** [comment]
if you really need help - find me in the telegram @Platonenkov 
and I will try to help

**Comment by rickgoud** [comment]
I found it. See screenshot below.
Current is null in my application. Zo adding the ? which was missing, solved the issue. However don't know if you think that should be handled differently?

![image](https://user-images.githubusercontent.com/13066218/144989350-510e671b-f7d6-4c8e-b1f6-b08ab9f4f016.png)

**Comment by Platonenkov** [comment]
I really don't understand how this entity can be null..

**Comment by Platonenkov** [comment]
if u can send merge, please. And i update it

**Comment by rickgoud** [comment]
Hey! I tried to push a branch with the change, but it says I don't have permissions?

**Comment by Platonenkov** [comment]
just do this:
go to Pull in git
![image](https://user-images.githubusercontent.com/44946855/145071757-989a1d1a-d6ea-4c41-a22f-7b080e12dfbf.png)


- press link "1"
- select my project and "dev" branch ("2")
- select your branch ("3")
![image](https://user-images.githubusercontent.com/44946855/145071985-fa87ab63-a51a-4eb0-aab3-a95e4bd08d4f.png)

**Comment by Platonenkov** [comment]
Completed in v6.1.0.2, test it please.
