### ISSUE TITLE
Анализаторы Microsoft.DependencyValidation.Analyzers

### ISSUE THREAD

**Issue by Kiriller12** [Platonenkov/Notification.Wpf#40]
Здравствуйте, не могли бы вы исключить пакет с анализаторами Microsoft.DependencyValidation.Analyzers из зависимостей поставляемых с nuget-пакетом?

В нашем проекте не используются диаграммы зависимостей и связанные с ними анализаторы, но так как анализаторы подтягиваются вместе с пакетом уведомлений, из-за этого возникают предупреждения.

**Comment by Platonenkov** [comment]
I think it is possible, in reality I don't even remember how she appeared there )))

**Comment by Platonenkov** [comment]
check new version [v6.1.0.3](https://github.com/Platonenkov/Notification.Wpf/releases/tag/v6.1.0.3) please

**Comment by Kiriller12** [comment]
Yes, it works! Thank you!
