### ISSUE TITLE
Notifications does not work properyly when we have two monitor

### ISSUE THREAD

**Issue by batuhancengiz** [Platonenkov/Notification.Wpf#46]
Hello,

notifications in my main monitor work really properly but when i carry the app from main monitor to second monitor, occurs a problem like in photo.

![photo](https://user-images.githubusercontent.com/82826094/162139898-75ccfe0f-12bf-4962-b75a-408c21e8dff8.png)

How can i handle it?   

![photo2](https://user-images.githubusercontent.com/82826094/162140578-65ca2f95-55b5-489c-bef4-6d621b725744.png)

Another problem is resizing the app. When i minimize app and trigger the notification, i should see the notifications in my app. How can i make this?

Thanks for help!

**Comment by Platonenkov** [comment]
1) unfortunately, I could not repeat  first bug...
2) to display messages inside the window, you need to use the Area
Notification inside application window:
Adding namespace:
```XAML
xmlns:notifications="clr-namespace:Notification.Wpf.Controls;assembly=Notification.Wpf"
```
Adding new NotificationArea:
```XAML
<notifications:NotificationArea x:Name="WindowArea" Position="TopLeft" MaxItems="3"/>
```
Displaying notification:
```C#
notificationManager.Show(title, Message, type, "WindowArea", onClick: () => SomeAction();
```

look in the sample project (line 52) 
https://github.com/Platonenkov/Notification.Wpf/blob/dev/Notifications.Wpf.Sample/Views/SampleWindow.xaml

**Comment by batuhancengiz** [comment]
You are the best!
