### ISSUE TITLE
NotificationManager keeps references to NotificationArea from closed window

### ISSUE THREAD

**Issue by RParkerM** [Platonenkov/Notification.Wpf#61]
Hello, 

Thank you for maintaining this library, it's very helpful for adding notifications to my application.

I noticed that `NotificationManager` has a static readonly field `Areas` which contains a list of `NotificationArea`s. When a NotificationArea gets constructed, it calls `NotificationManager.AddArea(this)`. However, if the parent window of the `NotificationArea` is closed, the `Areas` field continues to hold a reference to it, keeping the parent (and anything that it references) from being GC'd.

I suggest adding a function to the `NotificationManager` class to remove areas which are no longer in use. Example below:
```csharp
internal static void RemoveArea(NotificationArea area) => Areas.Remove(area);
```
You could then remove the `NotificationArea` from the `Area` list when it is unloaded.
```csharp
private void NotificationArea_Unloaded(object sender, RoutedEventArgs e)
{
    NotificationManager.RemoveArea(this);
}
```

When doing this, the NotificationArea will be removed when the control is Unloaded, so I suggest moving the call to `NotificationManager.AddArea()` to the control's Loaded event rather than in its constructor, in case of the control being removed and added to the visual tree through something like navigation.

**Comment by Platonenkov** [comment]
Hi mate,
You can supplement the code and send Pull request, I will definitely look at the solution.

**Comment by Platonenkov** [comment]
updated to v7.0.0.2

Thank you.
