### ISSUE TITLE
Z index problem

### ISSUE THREAD

**Issue by batuhancengiz** [Platonenkov/Notification.Wpf#63]
Hello everyone,

Notification message is behind of the popup and is there any way to move to front of the window?

My xaml code:
```
        <notifications:NotificationArea x:Name="WindowArea" Position="BottomRight" MaxItems="3" Panel.ZIndex="999"
                                        Grid.RowSpan="2" />
```

My cs code:

```
            var title = LocalizationProvider.Instance[type.ToString()];
            var content = new NotificationContent
            {
                Title = title,
                Message = message,
                Type = type,
                Background = brush,
            };
            _notificationManager.Show(content, "WindowArea");
```

![image](https://github.com/Platonenkov/Notification.Wpf/assets/82826094/1dabfa1f-b266-4b01-8dff-85efe166c124)

**Comment by Platonenkov** [comment]
Everything is quite simple.
when you specify WindowsArea, you place messages in a specific window.
Simply do not specify this property, it is needed to display local messages.

**Comment by batuhancengiz** [comment]
Yeah, but I have to give windowsarea because when I minimize the application, then popup is opened bottom right corner of windows not in application. So is there a solution to cover both problem?

**Comment by batuhancengiz** [comment]
Actually my wish is simple. I just would like to have a notification on bottom right center and always looks in application (not corner of popup, corner of application) and looks always top on application. So can you do that your library or not?
