### ISSUE TITLE
Still have z index problem

### ISSUE THREAD

**Issue by batuhancengiz** [Platonenkov/Notification.Wpf#64]
Yeah, but I have to give windowsarea because when I minimize the application, then popup is opened bottom right corner of windows not in application. So is there a solution to cover both problem?

_Originally posted by @batuhancengiz in https://github.com/Platonenkov/Notification.Wpf/issues/63#issuecomment-1744781580_

**Comment by Platonenkov** [comment]
you need to formulate the question or task in more detail.

How it works now,
what it should look like, 
what it doesn't work, 
how you achieved this result.
